### ISSUE TITLE
athena-cli macOS

### ISSUE THREAD

**Issue by ghost** [guardian/athena-cli#26]
athena cli throws error on macOS but works fine on linux.

**Comment by satterly** [comment]
It works on my macbook, which I used to develop it on. What is the error? Can you copy and paste it below? Thanks.

**Comment by ghost** [comment]
Mac OS version : 10.13.2 
Below is the error
Traceback (most recent call last):
  File "/usr/local/bin/athena", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/athena_cli.py", line 406, in main
    shell.cmdloop_with_cancel()
  File "/Library/Python/2.7/site-packages/athena_cli.py", line 98, in cmdloop_with_cancel
    self.cmdloop(intro)
  File "/Library/Python/2.7/site-packages/cmd2.py", line 1950, in cmdloop
    self.preloop()
  File "/Library/Python/2.7/site-packages/athena_cli.py", line 110, in preloop
    readline.read_history_file(self.hist_file)
IOError: [Errno 1] Operation not permitted

**Comment by satterly** [comment]
This is an error related to the history file. Does the file `~/.athena_history` exist and readable by you? If it doesn't exist, maybe you could create it with the right permissions and try `athena` again.

**Comment by ghost** [comment]
yes, the file exist and is readable by me.

**Comment by ghost** [comment]
@satterly Anything else i could try to make it work ?

**Comment by satterly** [comment]
you could use python3 instead of the system installed python2. this is what I do otherwise you sometimes have to do `sudo pip install ...` to get things to install on macOS which is bad.

i use brew to install python3 but you could also download and install the python3 package from here ... https://www.python.org/downloads/mac-osx/

To install using brew...
```
$ brew install python3
```
and then anywhere that you would have normally used `pip` use `pip3` instead. For example...
```
$ pip3 install athena-cli
```

**Comment by ghost** [comment]
@satterly Installing python3 and using pip3 worked. Thanks.
